void startGame() ;
void fixDataValues() ;
void goSlowToRight() ;
void goSlowToLeft() ;
void goFastToRight() ;
void goFastToLeft() ;
void fixBorder() ;
void firstCar() ;
void sacondCar() ;
void displayImage() ;
void carCrash ()  ;
void game_over() ;
void speed () ;
long Check(long X , long x , long y ) ;
